
import ArchiveFilter from '@/components/ArchiveFilter/page';
import ArchiveList from '@/components/ArchiveList/page';
import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: "Архив - Госфильмофонд России",
	description: "Generated by create next app",
};

export default function ArchivePage() {
	return (
		<main className="main p-15">
			<div className="container mx-auto">
				<section className="py-15">
					<div className="text-center">
						<h1 className="text-4xl text-black-100 font-semibold mb-4">Архив</h1>
						<p className="text-1xl font-normal text-gray-500">Все новости</p>
					</div>
					<ArchiveFilter />
					<ArchiveList />
				</section>
			</div>
		</main>
	)
}