import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./style.page.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const font = Inter({
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Госфильмофонд России",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} no-scrollbar`}
      >
				<Header/>
        {children}
				<Footer/>
      </body>
    </html>
  );
}
