
import '@/components/DocumentsFilter/style.css';
import DocumentsList from '@/components/DocumentsList/DocumentsList';
import type { Metadata } from 'next';
import DocumentsFilter from '@/components/DocumentsFilter/DocumentsFilter';

export const metadata: Metadata = {
  title: "Документы - Госфильмофонд России",
  description: "Generated by create next app",
};

export default function DocumentsPage() {
  return (
    <main className="main p-15">
      <div className="container mx-auto">
        <section className="py-15">
          <div className="text-center">
            <h1 className="text-4xl text-black-100 font-semibold mb-4">Официальные документы</h1>
            <p className="text-1xl font-normal text-gray-500">Приказы, положения, отчеты и другие документы Госфильмофонда</p>
          </div>
          <DocumentsFilter />
          <DocumentsList />
        </section>
      </div>
    </main>
  );
}